FROM python:3.7-stretch

# Airflow
ARG AIRFLOW__CORE__DAGS_FOLDER
ARG AIRFLOW__CORE__BASE_LOG_FOLDER
ARG AIRFLOW__CORE__DAG_PROCESSOR_MANAGER_LOG_LOCATION
ARG AIRFLOW__CORE__SQL_ALCHEMY_CONN
ARG AIRFLOW__CORE__PLUGINS_FOLDER
ARG AIRFLOW__CORE__EXECUTOR
ARG AIRFLOW__CORE__FERNET_KEY
ARG AIRFLOW__SCHEDULER__CHILD_PROCESS_LOG_DIRECTORY
ARG AIRFLOW__SCHEDULER__STATSD_ON
ARG AIRFLOW__WEBSERVER__ERROR_LOGFILE
ARG AIRFLOW__WEBSERVER__ACCESS_LOGFILE
ARG AWHERE_TOKEN_URL
ARG AWHERE_ENCODED_KEY

# Define en_US.
ENV AIRFLOW_HOME=/usr/local/airflow
ENV AIRFLOW__CORE__BASE_LOG_FOLDER=${AIRFLOW__CORE__BASE_LOG_FOLDER}
ENV AIRFLOW__CORE__DAG_PROCESSOR_MANAGER_LOG_LOCATION=${AIRFLOW__CORE__DAG_PROCESSOR_MANAGER_LOG_LOCATION}
ENV AIRFLOW__CORE__SQL_ALCHEMY_CONN=${AIRFLOW__CORE__SQL_ALCHEMY_CONN}
ENV AIRFLOW__CORE__PLUGINS_FOLDER=${AIRFLOW__CORE__PLUGINS_FOLDER}
ENV AIRFLOW__CORE__EXECUTOR=${AIRFLOW__CORE__EXECUTOR}
ENV AIRFLOW__CORE__FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY}
ENV AIRFLOW__SCHEDULER__CHILD_PROCESS_LOG_DIRECTORY=${AIRFLOW__SCHEDULER__CHILD_PROCESS_LOG_DIRECTORY}
ENV AIRFLOW__SCHEDULER__STATSD_ON=${AIRFLOW__SCHEDULER__STATSD_ON}
ENV AIRFLOW__WEBSERVER__ERROR_LOGFILE=${AIRFLOW__WEBSERVER__ERROR_LOGFILE}
ENV AIRFLOW__WEBSERVER__ACCESS_LOGFILE=${AIRFLOW__WEBSERVER__ACCESS_LOGFILE}
ENV AWHERE_TOKEN_URL=${AWHERE_TOKEN_URL}
ENV AWHERE_ENCODED_KEY=${AWHERE_ENCODED_KEY}

ENV LANGUAGE en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8
ENV LC_CTYPE en_US.UTF-8
ENV LC_MESSAGES en_US.UTF-8

ADD ./dags $AIRFLOW_HOME/dags
ADD ./config/airflow.cfg $AIRFLOW_HOME/
ADD ./config/requirements.txt $AIRFLOW_HOME/
ADD ./plugins $AIRFLOW_HOME/plugins
ADD ./scripts $AIRFLOW_HOME/scripts
ADD ./entrypoint.sh $AIRFLOW_HOME/

WORKDIR "/usr/local/airflow"

RUN pip3 install -r requirements.txt

ENV PYTHONPATH=$PYTHONPATH:$AIRFLOW_HOME

EXPOSE 8080

RUN chmod u+x entrypoint.sh
RUN chmod +x scripts/etl/*.py

ENTRYPOINT ["/usr/local/airflow/entrypoint.sh"]
CMD ["webserver"]
